### ISSUE TITLE
Seperate test from .travis.yml

### ISSUE THREAD

**Issue by kidmose** [dnscryptio/dnscrypt-wrapper-docker#12]
Currently testing is implemented as a `script:` in `.travis.yml`.
This needs to be moved out to a separate test suite under under a `test` folder in the root of the repository, in order to be invoked from travis, manually/locally or elsewhere.
At the same time it will unclutter `.travis.yml`.

For a start I suggest a simple bash script.
This will allows us to gain the above improvements, without introducing further dependencies, such as a given test framework.

This issue is also mentioned, among others, in #11.

**Comment by simonclausen** [comment]
Solved by #13
