### ISSUE TITLE
Generation of provider key pair fails: "A provider key pair already exists."

### ISSUE THREAD

**Issue by kidmose** [dnscryptio/dnscrypt-wrapper-docker#7]
Trying to generate provider key pair fails as per the following:

    user@host ~ $ docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR dnscryptio/dnscrypt-wrapper --version
    dnscrypt-wrapper 0.2.2
    user@host ~ $ docker images | grep wrapper
    dnscryptio/dnscrypt-wrapper   latest              862e1c7a0181        8 weeks ago         290.2 MB
    user@host ~ $ docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR dnscryptio/dnscrypt-wrapper --gen-provider-keypair | tee /tmp/gen-provider-keypair.log
    Generate provider key pair... ok.
    Public key fingerprint: 2F74:63A8:26B4:9A53:CB9F:D27A:D0F9:2742:438B:3337:6C75:948F:369B:C6EB:9972:871F
    
    This is the provider key you should give to users for your service.
    (i.e. dnscrypt-proxy --provider-key=2F74:63A8:26B4:9A53:CB9F:D27A:D0F9:2742:438B:3337:6C75:948F:369B:C6EB:9972:871F
                         --resolver-address=<your resolver public IP>
                         --provider-name=2.dnscrypt-cert...)
    
    
    *KEYS HAVE NOT BEEN SAVED*
    
    A provider key pair already exists.
    If you really want to overwrite it, delete the public.key and secret.key files.
    
    The provider public key is what client give to dnscrypt-proxy
    in order to use your service (long-term key).
    
    Unless the private key has been compromised, you probably do not
    want to overwrite it with a new one.
    
    Usually, what you want (if current certificates are about to expire)
    to regenerate is the server key pairs (--gen-crypt-keypair),
    not the master keys.

Setting working directory with `-w` solves this:

    user@host ~ $ docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscryptio/dnscrypt-wrapper --gen-provider-keypair | tee /tmp/gen-provider-keypair.log
    Generate provider key pair... ok.
    Public key fingerprint: 56BD:2CE0:48E1:3D0C:69DC:7E97:47F4:1372:154E:AAD1:31DA:B347:9DE0:ABEF:5385:0E03
    
    This is the provider key you should give to users for your service.
    (i.e. dnscrypt-proxy --provider-key=56BD:2CE0:48E1:3D0C:69DC:7E97:47F4:1372:154E:AAD1:31DA:B347:9DE0:ABEF:5385:0E03
                         --resolver-address=<your resolver public IP>
                         --provider-name=2.dnscrypt-cert...)
    Keys are stored in public.key & secret.key.
    user@host ~ $ ll $HKEYDIR 
    total 44
    drwxr-xr-x  2 user user  4096 Jul 31 17:49 ./
    drwx------ 62 user user 16384 Jul 31 17:49 ../
    -r--r--r--  1 user user    32 Jul 31 17:49 public.key
    -r--r--r--  1 user user    64 Jul 31 17:49 secret.key

Supposedly, the error is misleading, as there are no files in the images. 
Further investigation is needed.

**Comment by simonclausen** [comment]
So it seems this is caused by one not being able to set permissions on a bind mount in Docker. How setting working dir have "fixed" this in previous examples, I have no idea.

**Comment by kidmose** [comment]
Finally got around to play with this, to understand the issue.
Transcript of successful run:

 * ~~Without `-w`~~
 * Using volumes instead of mounts <- this solves the problem

Snippet:

    user@user-laptop ~ $ HKEYDIR="hkeyvolume"
    user@user-laptop ~ $ CKEYDIR=/opt/dnscrypt-wrapper/etc/keys
    user@user-laptop ~ $ docker run --interactive --tty --rm --volume $HKEYDIR:$CKEYDIR -w $CKEYDIR dnscryptio/dnscrypt-wrapper --gen-provider-keypair
    Unable to find image 'dnscryptio/dnscrypt-wrapper:latest' locally
    latest: Pulling from dnscryptio/dnscrypt-wrapper
    94ed0c431eb5: Pull complete 
    37e96286792e: Pull complete 
    7dc3ae654f94: Pull complete 
    9af49d365b4a: Pull complete 
    aa4183116a91: Pull complete 
    Digest: sha256:601134e5f63d8be4e0961fb492a264167c611bffba60b5bf7a5c206bd711070a
    Status: Downloaded newer image for dnscryptio/dnscrypt-wrapper:latest
    Generate provider key pair... ok.
    Provider public key: 2A8E:44EA:AFF9:BF64:6D78:1F4B:53DE:330D:A313:1860:A028:AF07:CC8B:A35E:9D93:8518
    
    This is the provider key you should give to users for your service.
    (i.e. dnscrypt-proxy --provider-key=2A8E:44EA:AFF9:BF64:6D78:1F4B:53DE:330D:A313:1860:A028:AF07:CC8B:A35E:9D93:8518
                         --resolver-address=<your resolver public IP>
                         --provider-name=2.dnscrypt-cert...)
    Keys are stored in public.key & secret.key.
    user@user-laptop ~ $ docker volume ls 
    DRIVER              VOLUME NAME
    local               hkeyvolume
    user@user-laptop ~ $ docker volume inspect hkeyvolume 
    [
        {
            "Driver": "local",
            "Labels": null,
            "Mountpoint": "/var/lib/docker/volumes/hkeyvolume/_data",
            "Name": "hkeyvolume",
            "Options": {},
            "Scope": "local"
        }
    ]
    user@user-laptop ~ $ sudo ls -la /var/lib/docker/volumes/hkeyvolume/_data
    total 16
    drwxr-xr-x 2 user user 4096 Oct 11 21:35 .
    drwxr-xr-x 3 root root 4096 Oct 11 21:35 ..
    -r--r--r-- 1 user user   32 Oct 11 21:35 public.key
    -r-------- 1 user user   64 Oct 11 21:35 secret.key
