### ISSUE TITLE
Use packaged libsodium

### ISSUE THREAD

**Issue by simonclausen** [dnscryptio/dnscrypt-wrapper-docker#9]
Do we want to switch over to using the libsodium packaged in Debian versus compiling it as part of the build?

**Comment by kidmose** [comment]
Yes, if it the version requirement is met.
I think getting dependencies from debian's repositories is cleaner than retrieving and building them ourself.

**Comment by jedisct1** [comment]
I wouldn't recommend that since Debian ships with a version that didn't support xchacha20.

**Comment by kidmose** [comment]
I don't understand the implications of that, but I'm all for heeding your non-recomendation @jedisct1.
@simonclausen mentioned that we might not currently build libsodium with xchacha20 enabled.
Something we should look into? (I.e. what difference does it make?)

**Comment by simonclausen** [comment]
Thanks for getting back @jedisct1.

We're building with support chacha20 in libsodium. But I'm not sure if the wrapper build is picking up on it out of the box? Looking at build output from @kidmose' latest commit on PR.

The image we have on docker hub right now is dnscrypt-wrapper 0.2.2, so that would not have it.

**Comment by simonclausen** [comment]
It looks like building "full" libsodium will make the dnscrypt-wrapper build pick up on xchacha20: `Support for xchacha20: yes`

**Comment by simonclausen** [comment]
Ok, I guess we're okay here:
- We will keep building libsodium over using the Debian supplied package. For now at least.
- We are building and releasing the dnscrypt-wrapper Docker image with xchacha20: https://travis-ci.org/dnscryptio/dnscrypt-wrapper-docker/builds/265297411#L1746
